server:
  port: 7070
spring:
  application:
    name: bank-statement
  ##### Datasource Configuration #####
  datasource:
    driver-class-name: net.ucanaccess.jdbc.UcanaccessDriver
    url: jdbc:ucanaccess://D:/accountsdb.accdb;openExclusive=false;ignoreCase=true
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      dialect: org.hibernate.dialect.SQLServerDialect
#    archive:
#      autodetection: class